//Hämtar hela listan
GET http://localhost:3000/api/favoritesweets

###

//Hämtar ett visst ID
GET http://localhost:3000/api/favoritesweets/2/

###
//Tar bort ett visst ID
DELETE http://localhost:3000/api/favoritesweets/2/

###
PUT http://localhost:3000/api/favoritesweets/2/
Content-Type: application/json

{
    "id": 55,
    "name": "kjjj", 
    "origin": "New Zealand",
    "inventor": "ändraokr"
}

###
POST http://localhost:3000/api/favoritesweets/
Content-Type: application/json

{
    "id": 1,
    "name": "kola", 
    "origin": "New Zealand",
    "inventor": "Helen Leach"

}