//Hämtar hela listan
GET http://localhost:3000/api/favoritesweets

###

//Hämtar ett visst ID
GET http://localhost:3000/api/favoritesweets/1/

###
//Tar bort ett visst ID
DELETE http://localhost:3000/api/favoritesweets/2

###
//Uppdaterar ett objekt
PUT http://localhost:3000/api/favoritesweets/3/
Content-Type: application/json

{
    "name": "Change this", 
    "origin": "Change this",
    "inventor": "Change this"
}

###
//Lägger till ett nytt objekt
POST http://localhost:3000/api/favoritesweets/
Content-Type: application/json

{
    "name": "Add a new sweet", 
    "origin": "New origin",
    "inventor": "New inventor!"

}